### PR TITLE
Making Schema consistent with Topic names

### PR DESCRIPTION
**Pull request by Vidushi-GitHub**

### CODE REVIEW

**Comment by Vidushi-GitHub** [comment]
Following https://github.com/nasa-gcn/gcn.nasa.gov/issues/1539

**Comment by lpsinger** [comment]
@Vidushi-GitHub, would you please prepare a PR for the web site to update the naming conventions?

Also, should we change the naming convention of the core schema?

**Comment by Vidushi-GitHub** [comment]
> @Vidushi-GitHub, would you please prepare a PR for the web site to update the naming conventions?
> 
> Also, should we change the names of the core schema to match?

Changing the core-schema isn't necessary, we can keep basic/team ones as CamelCase. Whereas, producers ones as underscore, lowercase? The document only talk about naming convention for producers.

**Comment by blaufuss** [comment]
This is fine with IceCube.  We would need to make sure we change our production notices for the LVK  followup notices to match the new schema name, but can make a coordinated change once this is ready to go into production.

The move of the Gold/Bronze stuff to test/ was on purpose?  Once we get ready to produce these, we need to make a PR to move?  Thanks

**Review by blaufuss — APPROVED** [review]

**Comment by Vidushi-GitHub** [comment]
> The move of the Gold/Bronze stuff to test/ was on purpose? Once we get ready to produce these, we need to make a PR to move? Thanks

Although it's not in production, topic is already created as gcn.notices.icecube.test.gold_bronze_track_alerts.

**Comment by blaufuss** [comment]
> > The move of the Gold/Bronze stuff to test/ was on purpose? Once we get ready to produce these, we need to make a PR to move? Thanks
> 
> Although it's not in production, topic is already created as gcn.notices.icecube.test.gold_bronze_track_alerts and schema should have same structure. If you want please let's us know the modification in topic name for this one, that will be followed for schema name.

I understand the renaming to match the topic name, this is fine.  I also note the files here are moved to a ./test/ directory as part of this PR.  That's an intentional move?   It's fine if so, once we finish preparing it for production we can make a PR to move out of test...

**Comment by Vidushi-GitHub** [comment]
> I understand the renaming to match the topic name, this is fine. I also note the files here are moved to a ./test/ directory as part of this PR. That's an intentional move? It's fine if so, once we finish preparing it for production we can make a PR to move out of test...

If you go to issue: https://github.com/nasa-gcn/gcn.nasa.gov/issues/1539, gold/bronze has existing topic name as; gcn.notices.icecube.test.gold_bronze_track_alerts, which implies gcn/notices/icecube/test/ directory structure.

**Comment by Vidushi-GitHub** [comment]
> @Vidushi-GitHub, would you please prepare a PR for the web site to update the naming conventions?

Please see for PR#1540 for web site update.

**Review by lpsinger — APPROVED** [review]

**Pull request merged**
