### PR TITLE
Change for snake_case consistency

### PR DESCRIPTION
**Pull request by Vidushi-GitHub**
# Description
Change in mission schema name "Capital" to "Lower case".
It's getting validated for $schema properties.

### CODE REVIEW

**Comment by lpsinger** [comment]
Good catch, @Vidushi-GitHub. Before we merge this, I'd like to make sure that our validation script catches case mismatches in `$ref` and `$schema` fields.

**Comment by lpsinger** [comment]
OK, our validation script _is_ case sensitive. No problem there.

**Review by lpsinger — APPROVED** [review]
This looks fine to me, but we need someone from BurstCube to be aware of the change. Please find and add an appropriate BurstCube team member as a reviewer.

**Comment by Vidushi-GitHub** [comment]
This one is Glowbug, they aren't active. @jracusin What should be done?

**Comment by lpsinger** [comment]
> This one is Glowbug, they aren't active. @jracusin What should be done?

Sorry, of course I meant Glowbug. Is that Boyan?

**Comment by Vidushi-GitHub** [comment]
> > This one is Glowbug, they aren't active. @jracusin What should be done?
> 
> Sorry, of course I meant Glowbug. Is that Boyan?

Yes, Boyan created this one.

**Comment by lpsinger** [comment]
@shb46, would you please review this?

**Comment by lpsinger** [comment]
Is this a duplicate of #149?

**Comment by Vidushi-GitHub** [comment]
@shb46 although you aren't working on this anymore. 
But because of our schema policy, we need producers permission before merging the mission schema.

I am just closing the old PR, could you please approve (if looks fine) this?

**Comment by shb46** [comment]
@Vidushi-GitHub: Thanks for fixing the typo.

**Pull request closed without merging**
